### ISSUE TITLE
Search functionality on mobile view fix

### ISSUE THREAD

**Issue by b1khat** [Zacharius/eventsApp#17]
Filter needs to pass variable and display populate properly in page

**Comment by m-dabas** [comment]
@b1khat I'm a bit confused by the title. What problem am I trying to fix?

**Comment by nishantg95** [comment]
Hello @b1khat . Kindly provide more description as to what the current state of the issue is, and what needs to be done to fix it. If possible, also provide a screenshot of the bug you discovered, so that we can identify and resolve it together.

**Comment by b1khat** [comment]
@nishantg95 you are the one who come up with this issue.

**Comment by nishantg95** [comment]
I don't remember opening this issue with anything in regard to search functionality in terms of mobile view. Hence, I am closing this issue for now.
